spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym-ticket-batch?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    hikari:
      maximum-pool-size: 20

# 배치 기본 생성 테이블 생성 여부 설정
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: validate